/* Copyright 1990-2008, Jsoftware Inc.  All rights reserved.               */
/* Licensed use only. Any other use is in violation of copyright.          */
/*                                                                         */
/* Atomic Verbs                                                            */

// shorthands for inplacing
#define VIP (VIPOKA+VIPOKW)   // inplace everything
#define VIPI0 ((VIPOKA*(sizeof(I)==sizeof(D))))  // inplace left arg if D is same length as I
#define VIP0I ((VIPOKW*(sizeof(I)==sizeof(D))))  // inplace right arg if D is same length as I
#define VIPID (VIPI0+VIPOKW)  // inplace D, and I if I is same length as D: I is left arg
#define VIPDI (VIP0I+VIPOKA)  // inplace D, and I if I is same length as D: I is right arg

#define VIPW (VIPOKW)   // inplace is OK
#define VIP64 ((VIPOKW*(sizeof(I)==sizeof(D))))  // inplace monad if D is same length as I



//#define ADECL1  AHDR1
//#define ADECL2  AHDR2
#define ADECLP  AHDRP
#define ADECLR  AHDRR
#define ADECLS  AHDRS

extern I   absQ(JST * RESTRICT jt,I n,Q* z,Q* x);
extern I   absX(JST * RESTRICT jt,I n,X* z,X* x);
extern I  ceilQ(JST * RESTRICT jt,I n,X* z,Q* x);
extern I   expX(JST * RESTRICT jt,I n,X* z,X* x);
extern I  factD(JST * RESTRICT jt,I n,D* z,D* x);
extern I  factI(JST * RESTRICT jt,I n,I* z,I* x);
extern I  factQ(JST * RESTRICT jt,I n,X* z,Q* x);
extern I  factX(JST * RESTRICT jt,I n,X* z,X* x);
extern I  factZ(JST * RESTRICT jt,I n,Z* z,Z* x);
extern I floorQ(JST * RESTRICT jt,I n,X* z,Q* x);
extern I   logX(JST * RESTRICT jt,I n,X* z,X* x);
extern I  logQD(JST * RESTRICT jt,I n,D* z,Q* x);
extern I  logQZ(JST * RESTRICT jt,I n,Z* z,Q* x);
extern I  logXD(JST * RESTRICT jt,I n,D* z,X* x);
extern I  logXZ(JST * RESTRICT jt,I n,Z* z,X* x);
extern I   pixX(JST * RESTRICT jt,I n,X* z,X* x);
extern I   sgnQ(JST * RESTRICT jt,I n,X* z,Q* x);
extern I   sgnX(JST * RESTRICT jt,I n,X* z,X* x);
extern I  sqrtQ(JST * RESTRICT jt,I n,Q* z,Q* x);
extern I  sqrtX(JST * RESTRICT jt,I n,X* z,X* x);

extern ADECLP(   andpfxB,B, B );  extern ADECLR(   andinsB,B, B );  extern ADECLS(   andsfxB,B, B );
extern ADECLP(   divpfxD,D, D );  extern ADECLR(   divinsD,D, D );  extern ADECLS(   divsfxD,D, D );
extern ADECLP(   divpfxZ,Z, Z );  extern ADECLR(   divinsZ,Z, Z );  extern ADECLS(   divsfxZ,Z, Z );
extern ADECLP(    eqpfxB,B, B );  extern ADECLR(    eqinsB,B, B );  extern ADECLS(    eqsfxB,B, B );
extern ADECLP(    gepfxB,B, B );  extern ADECLR(    geinsB,B, B );  extern ADECLS(    gesfxB,B, B );
extern ADECLP(    gtpfxB,B, B );  extern ADECLR(    gtinsB,B, B );  extern ADECLS(    gtsfxB,B, B );
extern ADECLP(    lepfxB,B, B );  extern ADECLR(    leinsB,B, B );  extern ADECLS(    lesfxB,B, B );
extern ADECLP(    ltpfxB,B, B );  extern ADECLR(    ltinsB,B, B );  extern ADECLS(    ltsfxB,B, B );
extern ADECLP(   maxpfxD,D, D );  extern ADECLR(   maxinsD,D, D );  extern ADECLS(   maxsfxD,D, D );
extern ADECLP(   maxpfxI,I, I );  extern ADECLR(   maxinsI,I, I );  extern ADECLS(   maxsfxI,I, I );
extern ADECLP(   maxpfxQ,Q, Q );                                    extern ADECLS(   maxsfxQ,Q, Q );
extern ADECLP(   maxpfxS,SB,SB);  extern ADECLR(   maxinsS,SB,SB);  extern ADECLS(   maxsfxS,SB,SB);
extern ADECLP(   maxpfxX,X, X );  extern ADECLR(   maxinsX,X, X );  extern ADECLS(   maxsfxX,X, X );
extern ADECLP(   minpfxD,D, D );  extern ADECLR(   mininsD,D, D );  extern ADECLS(   minsfxD,D, D );
extern ADECLP(   minpfxI,I, I );  extern ADECLR(   mininsI,I, I );  extern ADECLS(   minsfxI,I, I );
extern ADECLP(   minpfxQ,Q, Q );                                    extern ADECLS(   minsfxQ,Q, Q );
extern ADECLP(   minpfxS,SB,SB);  extern ADECLR(   mininsS,SB,SB);  extern ADECLS(   minsfxS,SB,SB);
extern ADECLP(   minpfxX,X, X );  extern ADECLR(   mininsX,X, X );  extern ADECLS(   minsfxX,X, X );
extern ADECLP( minuspfxB,I, B );  extern ADECLR( minusinsB,I, B );  extern ADECLS( minussfxB,I, B );
extern ADECLP( minuspfxD,D, D );  extern ADECLR( minusinsD,D, D );  extern ADECLS( minussfxD,D, D );
extern ADECLP( minuspfxI,I, I );  extern ADECLR( minusinsI,I, I );  extern ADECLS( minussfxI,I, I );
extern ADECLP( minuspfxQ,Q, Q );  
extern ADECLP( minuspfxO,D, I );  extern ADECLR( minusinsO,D, I );  extern ADECLS( minussfxO,D, I );
extern ADECLP( minuspfxX,X, X );  
extern ADECLP( minuspfxZ,Z, Z );  extern ADECLR( minusinsZ,Z, Z );  extern ADECLS( minussfxZ,Z, Z );
extern ADECLP(  nandpfxB,B, B );  extern ADECLR(  nandinsB,B, B );  extern ADECLS(  nandsfxB,B, B );
extern ADECLP(    nepfxB,B, B );  extern ADECLR(    neinsB,B, B );  extern ADECLS(    nesfxB,B, B );
extern ADECLP(    orpfxB,B, B );  extern ADECLR(   norinsB,B, B );  extern ADECLS(   norsfxB,B, B );
extern ADECLP(   norpfxB,B, B );  extern ADECLR(    orinsB,B, B );  extern ADECLS(    orsfxB,B, B );
extern ADECLP(  pluspfxB,I, B );  extern ADECLR(  plusinsB,I, B );  extern ADECLS(  plussfxB,I, B );
extern ADECLP(  pluspfxD,D, D );  extern ADECLR(  plusinsD,D, D );  extern ADECLS(  plussfxD,D, D );
extern ADECLP(  pluspfxI,I, I );  extern ADECLR(  plusinsI,I, I );  extern ADECLS(  plussfxI,I, I );
extern ADECLP(  pluspfxO,D, I );  extern ADECLR(  plusinsO,D, I );  extern ADECLS(  plussfxO,D, I );
extern ADECLP(  pluspfxQ,Q, Q );                                    extern ADECLS(  plussfxQ,Q, Q );
extern ADECLP(  pluspfxX,X, X );                                    extern ADECLS(  plussfxX,X, X );
extern ADECLP(  pluspfxZ,Z, Z );  extern ADECLR(  plusinsZ,Z, Z );  extern ADECLS(  plussfxZ,Z, Z );
extern ADECLP( tymespfxD,D, D );  extern ADECLR( tymesinsD,D, D );  extern ADECLS( tymessfxD,D, D );
extern ADECLP( tymespfxI,I, I );  extern ADECLR( tymesinsI,I, I );  extern ADECLS( tymessfxI,I, I );
extern ADECLP( tymespfxO,D, I );  extern ADECLR( tymesinsO,D, I );  extern ADECLS( tymessfxO,D, I );
extern ADECLP( tymespfxQ,Q, Q );                                    extern ADECLS( tymessfxQ,Q, Q );
extern ADECLP( tymespfxX,X, X );                                    extern ADECLS( tymessfxX,X, X );
extern ADECLP( tymespfxZ,Z, Z );  extern ADECLR( tymesinsZ,Z, Z );  extern ADECLS( tymessfxZ,Z, Z );

extern ADECLP(bw0000pfxI,UI,UI);  extern ADECLR(bw0000insI,UI,UI);  extern ADECLS(bw0000sfxI,UI,UI);
extern ADECLP(bw0001pfxI,UI,UI);  extern ADECLR(bw0001insI,UI,UI);  extern ADECLS(bw0001sfxI,UI,UI);
                                  extern ADECLR(bw0010insI,UI,UI);  extern ADECLS(bw0010sfxI,UI,UI);
extern ADECLP(bw0011pfxI,UI,UI);  extern ADECLR(bw0011insI,UI,UI);  extern ADECLS(bw0011sfxI,UI,UI);
                                  extern ADECLR(bw0100insI,UI,UI);  extern ADECLS(bw0100sfxI,UI,UI);
extern ADECLP(bw0101pfxI,UI,UI);  extern ADECLR(bw0101insI,UI,UI);  extern ADECLS(bw0101sfxI,UI,UI);
extern ADECLP(bw0110pfxI,UI,UI);  extern ADECLR(bw0110insI,UI,UI);  extern ADECLS(bw0110sfxI,UI,UI);
extern ADECLP(bw0111pfxI,UI,UI);  extern ADECLR(bw0111insI,UI,UI);  extern ADECLS(bw0111sfxI,UI,UI);
                                  extern ADECLR(bw1000insI,UI,UI);  extern ADECLS(bw1000sfxI,UI,UI);
extern ADECLP(bw1001pfxI,UI,UI);  extern ADECLR(bw1001insI,UI,UI);  extern ADECLS(bw1001sfxI,UI,UI);
                                  extern ADECLR(bw1010insI,UI,UI);  extern ADECLS(bw1010sfxI,UI,UI);
                                  extern ADECLR(bw1011insI,UI,UI);  extern ADECLS(bw1011sfxI,UI,UI);
                                  extern ADECLR(bw1100insI,UI,UI);  extern ADECLS(bw1100sfxI,UI,UI);
                                  extern ADECLR(bw1101insI,UI,UI);  extern ADECLS(bw1101sfxI,UI,UI);
                                  extern ADECLR(bw1110insI,UI,UI);  extern ADECLS(bw1110sfxI,UI,UI);
extern ADECLP(bw1111pfxI,UI,UI);  extern ADECLR(bw1111insI,UI,UI);  extern ADECLS(bw1111sfxI,UI,UI);

extern I bw0000II(I n,I m,UI* RESTRICTI x,UI* RESTRICTI y,UI* RESTRICTI z,J jt);
extern I bw0001II(I n,I m,UI* RESTRICTI x,UI* RESTRICTI y,UI* RESTRICTI z,J jt);
extern I bw0010II(I n,I m,UI* RESTRICTI x,UI* RESTRICTI y,UI* RESTRICTI z,J jt);
extern I bw0011II(I n,I m,UI* RESTRICTI x,UI* RESTRICTI y,UI* RESTRICTI z,J jt);
extern I bw0100II(I n,I m,UI* RESTRICTI x,UI* RESTRICTI y,UI* RESTRICTI z,J jt);
extern I bw0101II(I n,I m,UI* RESTRICTI x,UI* RESTRICTI y,UI* RESTRICTI z,J jt);
extern I bw0110II(I n,I m,UI* RESTRICTI x,UI* RESTRICTI y,UI* RESTRICTI z,J jt);
extern I bw0111II(I n,I m,UI* RESTRICTI x,UI* RESTRICTI y,UI* RESTRICTI z,J jt);
extern I bw1000II(I n,I m,UI* RESTRICTI x,UI* RESTRICTI y,UI* RESTRICTI z,J jt);
extern I bw1001II(I n,I m,UI* RESTRICTI x,UI* RESTRICTI y,UI* RESTRICTI z,J jt);
extern I bw1010II(I n,I m,UI* RESTRICTI x,UI* RESTRICTI y,UI* RESTRICTI z,J jt);
extern I bw1011II(I n,I m,UI* RESTRICTI x,UI* RESTRICTI y,UI* RESTRICTI z,J jt);
extern I bw1100II(I n,I m,UI* RESTRICTI x,UI* RESTRICTI y,UI* RESTRICTI z,J jt);
extern I bw1101II(I n,I m,UI* RESTRICTI x,UI* RESTRICTI y,UI* RESTRICTI z,J jt);
extern I bw1110II(I n,I m,UI* RESTRICTI x,UI* RESTRICTI y,UI* RESTRICTI z,J jt);
extern I bw1111II(I n,I m,UI* RESTRICTI x,UI* RESTRICTI y,UI* RESTRICTI z,J jt);

extern I   andBB(I n,I m,void* RESTRICTI x,void* RESTRICTI y,void* RESTRICTI z,J jt);
extern I   binDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   binQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,X* RESTRICTI z,J jt);
extern I   binXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,X* RESTRICTI z,J jt);
extern I   binZZ(I n,I m,Z* RESTRICTI x,Z* RESTRICTI y,Z* RESTRICTI z,J jt);
extern I   cirBD(I n,I m,B* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   cirID(I n,I m,I* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   cirDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   cirZZ(I n,I m,Z* RESTRICTI x,Z* RESTRICTI y,Z* RESTRICTI z,J jt);
extern I   divBB(I n,I m,B* RESTRICTI x,B* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   divBD(I n,I m,B* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   divBI(I n,I m,B* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   divDB(I n,I m,D* RESTRICTI x,B* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   divDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   divDI(I n,I m,D* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   divIB(I n,I m,I* RESTRICTI x,B* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   divID(I n,I m,I* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   divII(I n,I m,I* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   divQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,Q* RESTRICTI z,J jt);
extern I   divXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,X* RESTRICTI z,J jt);
extern I   divZZ(I n,I m,Z* RESTRICTI x,Z* RESTRICTI y,Z* RESTRICTI z,J jt);
extern I    eqAA(I n,I m,A* RESTRICTI x,A* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqBB(I n,I m,void* RESTRICTI x,void* RESTRICTI y,void* RESTRICTI z,J jt);
extern I    eqBD(I n,I m,B* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqBI(I n,I m,B* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqCC(I n,I m,void* RESTRICTI x,void* RESTRICTI y,void* RESTRICTI z,J jt);  // really B,C,C
extern I    eqCS(I n,I m,UC* RESTRICTI x,US* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqDB(I n,I m,D* RESTRICTI x,B* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqDI(I n,I m,D* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqIB(I n,I m,I* RESTRICTI x,B* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqID(I n,I m,I* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqII(I n,I m,I* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqSC(I n,I m,US* RESTRICTI x,UC* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqSS(I n,I m,S* RESTRICTI x,S* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqZZ(I n,I m,Z* RESTRICTI x,Z* RESTRICTI y,B* RESTRICTI z,J jt);
extern I   gcdDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   gcdII(I n,I m,I* RESTRICTI x,I* RESTRICTI y,I* RESTRICTI z,J jt);
extern I   gcdIO(I n,I m,I* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   gcdQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,Q* RESTRICTI z,J jt);
extern I   gcdXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,X* RESTRICTI z,J jt);
extern I   gcdZZ(I n,I m,Z* RESTRICTI x,Z* RESTRICTI y,Z* RESTRICTI z,J jt);
extern I    geBB(I n,I m,void* RESTRICTI x,void* RESTRICTI y,void* RESTRICTI z,J jt);
extern I    geBD(I n,I m,B* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    geBI(I n,I m,B* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    geDB(I n,I m,D* RESTRICTI x,B* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    geDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    geDI(I n,I m,D* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    geIB(I n,I m,I* RESTRICTI x,B* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    geID(I n,I m,I* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    geII(I n,I m,I* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    geQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    geSS(I n,I m,SB* RESTRICTI x,SB* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    geXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    gtBB(I n,I m,void* RESTRICTI x,void* RESTRICTI y,void* RESTRICTI z,J jt);
extern I    gtBD(I n,I m,B* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    gtBI(I n,I m,B* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    gtDB(I n,I m,D* RESTRICTI x,B* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    gtDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    gtDI(I n,I m,D* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    gtIB(I n,I m,I* RESTRICTI x,B* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    gtID(I n,I m,I* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    gtII(I n,I m,I* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    gtSS(I n,I m,SB* RESTRICTI x,SB* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    gtQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    gtXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,B* RESTRICTI z,J jt);
extern I   lcmDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   lcmII(I n,I m,I* RESTRICTI x,I* RESTRICTI y,I* RESTRICTI z,J jt);
extern I   lcmIO(I n,I m,I* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   lcmQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,Q* RESTRICTI z,J jt);
extern I   lcmXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,X* RESTRICTI z,J jt);
extern I   lcmZZ(I n,I m,Z* RESTRICTI x,Z* RESTRICTI y,Z* RESTRICTI z,J jt);
extern I    leBB(I n,I m,void* RESTRICTI x,void* RESTRICTI y,void* RESTRICTI z,J jt);
extern I    leBD(I n,I m,B* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    leBI(I n,I m,B* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    leDB(I n,I m,D* RESTRICTI x,B* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    leDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    leDI(I n,I m,D* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    leIB(I n,I m,I* RESTRICTI x,B* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    leID(I n,I m,I* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    leII(I n,I m,I* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    leQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    leSS(I n,I m,SB* RESTRICTI x,SB* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    leXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    ltBB(I n,I m,void* RESTRICTI x,void* RESTRICTI y,void* RESTRICTI z,J jt);
extern I    ltBD(I n,I m,B* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    ltBI(I n,I m,B* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    ltDB(I n,I m,D* RESTRICTI x,B* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    ltDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    ltDI(I n,I m,D* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    ltIB(I n,I m,I* RESTRICTI x,B* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    ltID(I n,I m,I* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    ltII(I n,I m,I* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    ltSS(I n,I m,SB* RESTRICTI x,SB* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    ltQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    ltXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,B* RESTRICTI z,J jt);
extern I   maxBD(I n,I m,B* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   maxBI(I n,I m,B* RESTRICTI x,I* RESTRICTI y,I* RESTRICTI z,J jt);
extern I   maxDB(I n,I m,D* RESTRICTI x,B* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   maxDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   maxDI(I n,I m,D* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   maxIB(I n,I m,I* RESTRICTI x,B* RESTRICTI y,I* RESTRICTI z,J jt);
extern I   maxID(I n,I m,I* RESTRICTI x,D* RESTRICTI y,I* RESTRICTI z,J jt);
extern I   maxII(I n,I m,I* RESTRICTI x,I* RESTRICTI y,I* RESTRICTI z,J jt);
extern I   maxQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,Q* RESTRICTI z,J jt);
extern I   maxSS(I n,I m,SB* RESTRICTI x,SB* RESTRICTI y,SB* RESTRICTI z,J jt);
extern I   maxXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,X* RESTRICTI z,J jt);
extern I   minBD(I n,I m,B* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   minBI(I n,I m,B* RESTRICTI x,I* RESTRICTI y,I* RESTRICTI z,J jt);
extern I   minDB(I n,I m,D* RESTRICTI x,B* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   minDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   minDI(I n,I m,D* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   minIB(I n,I m,I* RESTRICTI x,B* RESTRICTI y,I* RESTRICTI z,J jt);
extern I   minID(I n,I m,I* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   minII(I n,I m,I* RESTRICTI x,I* RESTRICTI y,I* RESTRICTI z,J jt);
extern I   minQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,Q* RESTRICTI z,J jt);
extern I   minSS(I n,I m,SB* RESTRICTI x,SB* RESTRICTI y,SB* RESTRICTI z,J jt);
extern I   minXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,X* RESTRICTI z,J jt);
extern I minusBB(I n,I m,B* RESTRICTI x,B* RESTRICTI y,I* RESTRICTI z,J jt);
extern I minusBD(I n,I m,B* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I minusBI(I n,I m,B* RESTRICTI x,I* RESTRICTI y,I* RESTRICTI z,J jt);
extern I minusBIO(I n,I m,B* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I minusDB(I n,I m,D* RESTRICTI x,B* RESTRICTI y,D* RESTRICTI z,J jt);
extern I minusDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I minusDI(I n,I m,D* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I minusIB(I n,I m,I* RESTRICTI x,B* RESTRICTI y,I* RESTRICTI z,J jt);
extern I minusID(I n,I m,I* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I minusII(I n,I m,I* RESTRICTI x,I* RESTRICTI y,I* RESTRICTI z,J jt);
extern I minusIIO(I n,I m,I* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I minusIO(I n,I m,I* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I minusQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,Q* RESTRICTI z,J jt);
extern I minusXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,X* RESTRICTI z,J jt);
extern I minusZZ(I n,I m,Z* RESTRICTI x,Z* RESTRICTI y,Z* RESTRICTI z,J jt);
extern I  nandBB(I n,I m,void* RESTRICTI x,void* RESTRICTI y,void* RESTRICTI z,J jt);
extern I    neAA(I n,I m,A* RESTRICTI x,A* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neBB(I n,I m,void* RESTRICTI x,void* RESTRICTI y,void* RESTRICTI z,J jt);
extern I    neBD(I n,I m,B* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neBI(I n,I m,B* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neCC(I n,I m,void* RESTRICTI x,void* RESTRICTI y,void* RESTRICTI z,J jt);  // really B,C,C
extern I    neCS(I n,I m,UC* RESTRICTI x,US* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neDB(I n,I m,D* RESTRICTI x,B* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neDI(I n,I m,D* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neIB(I n,I m,I* RESTRICTI x,B* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neID(I n,I m,I* RESTRICTI x,D* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neII(I n,I m,I* RESTRICTI x,I* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neSC(I n,I m,US* RESTRICTI x,UC* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neSS(I n,I m,S* RESTRICTI x,S* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neZZ(I n,I m,Z* RESTRICTI x,Z* RESTRICTI y,B* RESTRICTI z,J jt);
extern I   norBB(I n,I m,void* RESTRICTI x,void* RESTRICTI y,void* RESTRICTI z,J jt);
extern I    orBB(I n,I m,void* RESTRICTI x,void* RESTRICTI y,void* RESTRICTI z,J jt);
extern I  plusBB(I n,I m,B* RESTRICTI x,B* RESTRICTI y,I* RESTRICTI z,J jt);
extern I  plusBI(I n,I m,B* RESTRICTI x,I* RESTRICTI y,I* RESTRICTI z,J jt);
extern I  plusBIO(I n,I m,B* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I  plusBD(I n,I m,B* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I  plusDB(I n,I m,D* RESTRICTI x,B* RESTRICTI y,D* RESTRICTI z,J jt);
extern I  plusDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I  plusDI(I n,I m,D* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I  plusDX(I n,I m,DX* RESTRICTI x,DX* RESTRICTI y,DX* RESTRICTI z,J jt);
extern I  plusIB(I n,I m,I* RESTRICTI x,B* RESTRICTI y,I* RESTRICTI z,J jt);
extern I  plusID(I n,I m,I* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I  plusII(I n,I m,I* RESTRICTI x,I* RESTRICTI y,I* RESTRICTI z,J jt);
extern I  plusIIO(I n,I m,I* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I  plusIO(I n,I m,I* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I  plusQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,Q* RESTRICTI z,J jt);
extern I  plusXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,X* RESTRICTI z,J jt);
extern I  plusZZ(I n,I m,Z* RESTRICTI x,Z* RESTRICTI y,Z* RESTRICTI z,J jt);
extern I   powBD(I n,I m,B* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   powBI(I n,I m,B* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   powDB(I n,I m,D* RESTRICTI x,B* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   powDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   powDI(I n,I m,D* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   powIB(I n,I m,I* RESTRICTI x,B* RESTRICTI y,I* RESTRICTI z,J jt);
extern I   powID(I n,I m,I* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   powII(I n,I m,I* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   powQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,Q* RESTRICTI z,J jt);
extern I   powXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,X* RESTRICTI z,J jt);
extern I   powZZ(I n,I m,Z* RESTRICTI x,Z* RESTRICTI y,Z* RESTRICTI z,J jt);
extern I   remDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I   remII(I n,I m,I* RESTRICTI x,I* RESTRICTI y,I* RESTRICTI z,J jt);
extern I   remID(I n,I m,I* RESTRICTI x,D* RESTRICTI y,I* RESTRICTI z,J jt);
extern I   remQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,Q* RESTRICTI z,J jt);
extern I   remXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,X* RESTRICTI z,J jt);
extern I   remZZ(I n,I m,Z* RESTRICTI x,Z* RESTRICTI y,Z* RESTRICTI z,J jt);
extern I tymesBD(I n,I m,B* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I tymesBI(I n,I m,B* RESTRICTI x,I* RESTRICTI y,I* RESTRICTI z,J jt);
extern I tymesDB(I n,I m,D* RESTRICTI x,B* RESTRICTI y,D* RESTRICTI z,J jt);
extern I tymesDD(I n,I m,D* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I tymesDI(I n,I m,I* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I tymesIB(I n,I m,I* RESTRICTI x,B* RESTRICTI y,I* RESTRICTI z,J jt);
extern I tymesID(I n,I m,I* RESTRICTI x,D* RESTRICTI y,D* RESTRICTI z,J jt);
extern I tymesII(I n,I m,I* RESTRICTI x,I* RESTRICTI y,I* RESTRICTI z,J jt);
extern I tymesIIO(I n,I m,I* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I tymesIO(I n,I m,I* RESTRICTI x,I* RESTRICTI y,D* RESTRICTI z,J jt);
extern I tymesQQ(I n,I m,Q* RESTRICTI x,Q* RESTRICTI y,Q* RESTRICTI z,J jt);
extern I tymesXX(I n,I m,X* RESTRICTI x,X* RESTRICTI y,X* RESTRICTI z,J jt);
extern I tymesZZ(I n,I m,Z* RESTRICTI x,Z* RESTRICTI y,Z* RESTRICTI z,J jt);

extern I    eqUU(I n,I m,C4* RESTRICTI x,C4* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqUS(I n,I m,C4* RESTRICTI x,US* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqSU(I n,I m,US* RESTRICTI x,C4* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqUC(I n,I m,C4* RESTRICTI x,UC* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    eqCU(I n,I m,UC* RESTRICTI x,C4* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neUU(I n,I m,C4* RESTRICTI x,C4* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neUS(I n,I m,C4* RESTRICTI x,US* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neSU(I n,I m,US* RESTRICTI x,C4* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neUC(I n,I m,C4* RESTRICTI x,UC* RESTRICTI y,B* RESTRICTI z,J jt);
extern I    neCU(I n,I m,UC* RESTRICTI x,C4* RESTRICTI y,B* RESTRICTI z,J jt);
