/* Copyright 1990-2008, Jsoftware Inc.  All rights reserved.               */
/* Licensed use only. Any other use is in violation of copyright.          */
/*                                                                         */
/* Atomic Verbs                                                            */

// shorthands for inplacing
#define VIP (VIPOKA + VIPOKW)                        // inplace everything
#define VIPI0 ((VIPOKA * (sizeof(I) == sizeof(D))))  // inplace left arg if D is same length as I
#define VIP0I ((VIPOKW * (sizeof(I) == sizeof(D))))  // inplace right arg if D is same length as I
#define VIPID (VIPI0 + VIPOKW)  // inplace D, and I if I is same length as D: I is left arg
#define VIPDI (VIP0I + VIPOKA)  // inplace D, and I if I is same length as D: I is right arg

#define VIPW (VIPOKW)                                // inplace is OK
#define VIP64 ((VIPOKW * (sizeof(I) == sizeof(D))))  // inplace monad if D is same length as I

extern I absQ(JST* RESTRICT jt, I n, Q* z, Q* x);
extern I absX(JST* RESTRICT jt, I n, X* z, X* x);
extern I ceilQ(JST* RESTRICT jt, I n, X* z, Q* x);
extern I expX(JST* RESTRICT jt, I n, X* z, X* x);
extern I factD(JST* RESTRICT jt, I n, D* z, D* x);
extern I factI(JST* RESTRICT jt, I n, I* z, I* x);
extern I factQ(JST* RESTRICT jt, I n, X* z, Q* x);
extern I factX(JST* RESTRICT jt, I n, X* z, X* x);
extern I factZ(JST* RESTRICT jt, I n, Z* z, Z* x);
extern I floorQ(JST* RESTRICT jt, I n, X* z, Q* x);
extern I logX(JST* RESTRICT jt, I n, X* z, X* x);
extern I logQD(JST* RESTRICT jt, I n, D* z, Q* x);
extern I logQZ(JST* RESTRICT jt, I n, Z* z, Q* x);
extern I logXD(JST* RESTRICT jt, I n, D* z, X* x);
extern I logXZ(JST* RESTRICT jt, I n, Z* z, X* x);
extern I pixX(JST* RESTRICT jt, I n, X* z, X* x);
extern I sgnQ(JST* RESTRICT jt, I n, X* z, Q* x);
extern I sgnX(JST* RESTRICT jt, I n, X* z, X* x);
extern I sqrtQ(JST* RESTRICT jt, I n, Q* z, Q* x);
extern I sqrtX(JST* RESTRICT jt, I n, X* z, X* x);
extern I andpfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I andinsB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I andsfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I divpfxD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I divinsD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I divsfxD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I divpfxZ(I d, I n, I m, Z* RESTRICTI x, Z* RESTRICTI z, J jt);
extern I divinsZ(I d, I n, I m, Z* RESTRICTI x, Z* RESTRICTI z, J jt);
extern I divsfxZ(I d, I n, I m, Z* RESTRICTI x, Z* RESTRICTI z, J jt);
extern I eqpfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I eqinsB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I eqsfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I gepfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I geinsB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I gesfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I gtpfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I gtinsB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I gtsfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I lepfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I leinsB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I lesfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I ltpfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I ltinsB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I ltsfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I maxpfxD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I maxinsD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I maxsfxD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I maxpfxI(I d, I n, I m, I* RESTRICTI x, I* RESTRICTI z, J jt);
extern I maxinsI(I d, I n, I m, I* RESTRICTI x, I* RESTRICTI z, J jt);
extern I maxsfxI(I d, I n, I m, I* RESTRICTI x, I* RESTRICTI z, J jt);
extern I maxpfxQ(I d, I n, I m, Q* RESTRICTI x, Q* RESTRICTI z, J jt);
extern I maxsfxQ(I d, I n, I m, Q* RESTRICTI x, Q* RESTRICTI z, J jt);
extern I maxpfxS(I d, I n, I m, SB* RESTRICTI x, SB* RESTRICTI z, J jt);
extern I maxinsS(I d, I n, I m, SB* RESTRICTI x, SB* RESTRICTI z, J jt);
extern I maxsfxS(I d, I n, I m, SB* RESTRICTI x, SB* RESTRICTI z, J jt);
extern I maxpfxX(I d, I n, I m, X* RESTRICTI x, X* RESTRICTI z, J jt);
extern I maxinsX(I d, I n, I m, X* RESTRICTI x, X* RESTRICTI z, J jt);
extern I maxsfxX(I d, I n, I m, X* RESTRICTI x, X* RESTRICTI z, J jt);
extern I minpfxD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I mininsD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I minsfxD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I minpfxI(I d, I n, I m, I* RESTRICTI x, I* RESTRICTI z, J jt);
extern I mininsI(I d, I n, I m, I* RESTRICTI x, I* RESTRICTI z, J jt);
extern I minsfxI(I d, I n, I m, I* RESTRICTI x, I* RESTRICTI z, J jt);
extern I minpfxQ(I d, I n, I m, Q* RESTRICTI x, Q* RESTRICTI z, J jt);
extern I minsfxQ(I d, I n, I m, Q* RESTRICTI x, Q* RESTRICTI z, J jt);
extern I minpfxS(I d, I n, I m, SB* RESTRICTI x, SB* RESTRICTI z, J jt);
extern I mininsS(I d, I n, I m, SB* RESTRICTI x, SB* RESTRICTI z, J jt);
extern I minsfxS(I d, I n, I m, SB* RESTRICTI x, SB* RESTRICTI z, J jt);
extern I minpfxX(I d, I n, I m, X* RESTRICTI x, X* RESTRICTI z, J jt);
extern I mininsX(I d, I n, I m, X* RESTRICTI x, X* RESTRICTI z, J jt);
extern I minsfxX(I d, I n, I m, X* RESTRICTI x, X* RESTRICTI z, J jt);
extern I minuspfxB(I d, I n, I m, B* RESTRICTI x, I* RESTRICTI z, J jt);
extern I minusinsB(I d, I n, I m, B* RESTRICTI x, I* RESTRICTI z, J jt);
extern I minussfxB(I d, I n, I m, B* RESTRICTI x, I* RESTRICTI z, J jt);
extern I minuspfxD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I minusinsD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I minussfxD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I minuspfxI(I d, I n, I m, I* RESTRICTI x, I* RESTRICTI z, J jt);
extern I minusinsI(I d, I n, I m, I* RESTRICTI x, I* RESTRICTI z, J jt);
extern I minussfxI(I d, I n, I m, I* RESTRICTI x, I* RESTRICTI z, J jt);
extern I minuspfxQ(I d, I n, I m, Q* RESTRICTI x, Q* RESTRICTI z, J jt);
extern I minuspfxO(I d, I n, I m, I* RESTRICTI x, D* RESTRICTI z, J jt);
extern I minusinsO(I d, I n, I m, I* RESTRICTI x, D* RESTRICTI z, J jt);
extern I minussfxO(I d, I n, I m, I* RESTRICTI x, D* RESTRICTI z, J jt);
extern I minuspfxX(I d, I n, I m, X* RESTRICTI x, X* RESTRICTI z, J jt);
extern I minuspfxZ(I d, I n, I m, Z* RESTRICTI x, Z* RESTRICTI z, J jt);
extern I minusinsZ(I d, I n, I m, Z* RESTRICTI x, Z* RESTRICTI z, J jt);
extern I minussfxZ(I d, I n, I m, Z* RESTRICTI x, Z* RESTRICTI z, J jt);
extern I nandpfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I nandinsB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I nandsfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I nepfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I neinsB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I nesfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I orpfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I norinsB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I norsfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I norpfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I orinsB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I orsfxB(I d, I n, I m, B* RESTRICTI x, B* RESTRICTI z, J jt);
extern I pluspfxB(I d, I n, I m, B* RESTRICTI x, I* RESTRICTI z, J jt);
extern I plusinsB(I d, I n, I m, B* RESTRICTI x, I* RESTRICTI z, J jt);
extern I plussfxB(I d, I n, I m, B* RESTRICTI x, I* RESTRICTI z, J jt);
extern I pluspfxD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I plusinsD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I plussfxD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I pluspfxI(I d, I n, I m, I* RESTRICTI x, I* RESTRICTI z, J jt);
extern I plusinsI(I d, I n, I m, I* RESTRICTI x, I* RESTRICTI z, J jt);
extern I plussfxI(I d, I n, I m, I* RESTRICTI x, I* RESTRICTI z, J jt);
extern I pluspfxO(I d, I n, I m, I* RESTRICTI x, D* RESTRICTI z, J jt);
extern I plusinsO(I d, I n, I m, I* RESTRICTI x, D* RESTRICTI z, J jt);
extern I plussfxO(I d, I n, I m, I* RESTRICTI x, D* RESTRICTI z, J jt);
extern I pluspfxQ(I d, I n, I m, Q* RESTRICTI x, Q* RESTRICTI z, J jt);
extern I plussfxQ(I d, I n, I m, Q* RESTRICTI x, Q* RESTRICTI z, J jt);
extern I pluspfxX(I d, I n, I m, X* RESTRICTI x, X* RESTRICTI z, J jt);
extern I plussfxX(I d, I n, I m, X* RESTRICTI x, X* RESTRICTI z, J jt);
extern I pluspfxZ(I d, I n, I m, Z* RESTRICTI x, Z* RESTRICTI z, J jt);
extern I plusinsZ(I d, I n, I m, Z* RESTRICTI x, Z* RESTRICTI z, J jt);
extern I plussfxZ(I d, I n, I m, Z* RESTRICTI x, Z* RESTRICTI z, J jt);
extern I tymespfxD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I tymesinsD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I tymessfxD(I d, I n, I m, D* RESTRICTI x, D* RESTRICTI z, J jt);
extern I tymespfxI(I d, I n, I m, I* RESTRICTI x, I* RESTRICTI z, J jt);
extern I tymesinsI(I d, I n, I m, I* RESTRICTI x, I* RESTRICTI z, J jt);
extern I tymessfxI(I d, I n, I m, I* RESTRICTI x, I* RESTRICTI z, J jt);
extern I tymespfxO(I d, I n, I m, I* RESTRICTI x, D* RESTRICTI z, J jt);
extern I tymesinsO(I d, I n, I m, I* RESTRICTI x, D* RESTRICTI z, J jt);
extern I tymessfxO(I d, I n, I m, I* RESTRICTI x, D* RESTRICTI z, J jt);
extern I tymespfxQ(I d, I n, I m, Q* RESTRICTI x, Q* RESTRICTI z, J jt);
extern I tymessfxQ(I d, I n, I m, Q* RESTRICTI x, Q* RESTRICTI z, J jt);
extern I tymespfxX(I d, I n, I m, X* RESTRICTI x, X* RESTRICTI z, J jt);
extern I tymessfxX(I d, I n, I m, X* RESTRICTI x, X* RESTRICTI z, J jt);
extern I tymespfxZ(I d, I n, I m, Z* RESTRICTI x, Z* RESTRICTI z, J jt);
extern I tymesinsZ(I d, I n, I m, Z* RESTRICTI x, Z* RESTRICTI z, J jt);
extern I tymessfxZ(I d, I n, I m, Z* RESTRICTI x, Z* RESTRICTI z, J jt);
extern I bw0000pfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0000insI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0000sfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0001pfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0001insI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0001sfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0010insI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0010sfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0011pfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0011insI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0011sfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0100insI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0100sfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0101pfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0101insI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0101sfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0110pfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0110insI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0110sfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0111pfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0111insI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0111sfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1000insI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1000sfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1001pfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1001insI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1001sfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1010insI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1010sfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1011insI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1011sfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1100insI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1100sfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1101insI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1101sfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1110insI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1110sfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1111pfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1111insI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw1111sfxI(I d, I n, I m, UI* RESTRICTI x, UI* RESTRICTI z, J jt);
extern I bw0000II(I n, I m, UI* RESTRICTI x, UI* RESTRICTI y, UI* RESTRICTI z, J jt);
extern I bw0001II(I n, I m, UI* RESTRICTI x, UI* RESTRICTI y, UI* RESTRICTI z, J jt);
extern I bw0010II(I n, I m, UI* RESTRICTI x, UI* RESTRICTI y, UI* RESTRICTI z, J jt);
extern I bw0011II(I n, I m, UI* RESTRICTI x, UI* RESTRICTI y, UI* RESTRICTI z, J jt);
extern I bw0100II(I n, I m, UI* RESTRICTI x, UI* RESTRICTI y, UI* RESTRICTI z, J jt);
extern I bw0101II(I n, I m, UI* RESTRICTI x, UI* RESTRICTI y, UI* RESTRICTI z, J jt);
extern I bw0110II(I n, I m, UI* RESTRICTI x, UI* RESTRICTI y, UI* RESTRICTI z, J jt);
extern I bw0111II(I n, I m, UI* RESTRICTI x, UI* RESTRICTI y, UI* RESTRICTI z, J jt);
extern I bw1000II(I n, I m, UI* RESTRICTI x, UI* RESTRICTI y, UI* RESTRICTI z, J jt);
extern I bw1001II(I n, I m, UI* RESTRICTI x, UI* RESTRICTI y, UI* RESTRICTI z, J jt);
extern I bw1010II(I n, I m, UI* RESTRICTI x, UI* RESTRICTI y, UI* RESTRICTI z, J jt);
extern I bw1011II(I n, I m, UI* RESTRICTI x, UI* RESTRICTI y, UI* RESTRICTI z, J jt);
extern I bw1100II(I n, I m, UI* RESTRICTI x, UI* RESTRICTI y, UI* RESTRICTI z, J jt);
extern I bw1101II(I n, I m, UI* RESTRICTI x, UI* RESTRICTI y, UI* RESTRICTI z, J jt);
extern I bw1110II(I n, I m, UI* RESTRICTI x, UI* RESTRICTI y, UI* RESTRICTI z, J jt);
extern I bw1111II(I n, I m, UI* RESTRICTI x, UI* RESTRICTI y, UI* RESTRICTI z, J jt);
extern I andBB(I n, I m, void* RESTRICTI x, void* RESTRICTI y, void* RESTRICTI z, J jt);
extern I binDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I binQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, X* RESTRICTI z, J jt);
extern I binZZ(I n, I m, Z* RESTRICTI x, Z* RESTRICTI y, Z* RESTRICTI z, J jt);
extern I cirBD(I n, I m, B* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I cirID(I n, I m, I* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I cirDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I cirZZ(I n, I m, Z* RESTRICTI x, Z* RESTRICTI y, Z* RESTRICTI z, J jt);
extern I divBB(I n, I m, B* RESTRICTI x, B* RESTRICTI y, D* RESTRICTI z, J jt);
extern I divBD(I n, I m, B* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I divBI(I n, I m, B* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I divDB(I n, I m, D* RESTRICTI x, B* RESTRICTI y, D* RESTRICTI z, J jt);
extern I divDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I divDI(I n, I m, D* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I divIB(I n, I m, I* RESTRICTI x, B* RESTRICTI y, D* RESTRICTI z, J jt);
extern I divID(I n, I m, I* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I divII(I n, I m, I* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I divQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, Q* RESTRICTI z, J jt);
extern I divXX(I n, I m, X* RESTRICTI x, X* RESTRICTI y, X* RESTRICTI z, J jt);
extern I divZZ(I n, I m, Z* RESTRICTI x, Z* RESTRICTI y, Z* RESTRICTI z, J jt);
extern I eqAA(I n, I m, A* RESTRICTI x, A* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqBB(I n, I m, void* RESTRICTI x, void* RESTRICTI y, void* RESTRICTI z, J jt);
extern I eqBD(I n, I m, B* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqBI(I n, I m, B* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqCC(I n, I m, void* RESTRICTI x, void* RESTRICTI y, void* RESTRICTI z, J jt);  // really B,C,C
extern I eqCS(I n, I m, UC* RESTRICTI x, US* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqDB(I n, I m, D* RESTRICTI x, B* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqDI(I n, I m, D* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqIB(I n, I m, I* RESTRICTI x, B* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqID(I n, I m, I* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqII(I n, I m, I* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqSC(I n, I m, US* RESTRICTI x, UC* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqSS(I n, I m, S* RESTRICTI x, S* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqXX(I n, I m, X* RESTRICTI x, X* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqZZ(I n, I m, Z* RESTRICTI x, Z* RESTRICTI y, B* RESTRICTI z, J jt);
extern I gcdDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I gcdII(I n, I m, I* RESTRICTI x, I* RESTRICTI y, I* RESTRICTI z, J jt);
extern I gcdIO(I n, I m, I* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I gcdQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, Q* RESTRICTI z, J jt);
extern I gcdXX(I n, I m, X* RESTRICTI x, X* RESTRICTI y, X* RESTRICTI z, J jt);
extern I gcdZZ(I n, I m, Z* RESTRICTI x, Z* RESTRICTI y, Z* RESTRICTI z, J jt);
extern I geBB(I n, I m, void* RESTRICTI x, void* RESTRICTI y, void* RESTRICTI z, J jt);
extern I geBD(I n, I m, B* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I geBI(I n, I m, B* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I geDB(I n, I m, D* RESTRICTI x, B* RESTRICTI y, B* RESTRICTI z, J jt);
extern I geDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I geDI(I n, I m, D* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I geIB(I n, I m, I* RESTRICTI x, B* RESTRICTI y, B* RESTRICTI z, J jt);
extern I geID(I n, I m, I* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I geII(I n, I m, I* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I geQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, B* RESTRICTI z, J jt);
extern I geSS(I n, I m, SB* RESTRICTI x, SB* RESTRICTI y, B* RESTRICTI z, J jt);
extern I geXX(I n, I m, X* RESTRICTI x, X* RESTRICTI y, B* RESTRICTI z, J jt);
extern I gtBB(I n, I m, void* RESTRICTI x, void* RESTRICTI y, void* RESTRICTI z, J jt);
extern I gtBD(I n, I m, B* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I gtBI(I n, I m, B* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I gtDB(I n, I m, D* RESTRICTI x, B* RESTRICTI y, B* RESTRICTI z, J jt);
extern I gtDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I gtDI(I n, I m, D* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I gtIB(I n, I m, I* RESTRICTI x, B* RESTRICTI y, B* RESTRICTI z, J jt);
extern I gtID(I n, I m, I* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I gtII(I n, I m, I* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I gtSS(I n, I m, SB* RESTRICTI x, SB* RESTRICTI y, B* RESTRICTI z, J jt);
extern I gtQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, B* RESTRICTI z, J jt);
extern I gtXX(I n, I m, X* RESTRICTI x, X* RESTRICTI y, B* RESTRICTI z, J jt);
extern I lcmDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I lcmII(I n, I m, I* RESTRICTI x, I* RESTRICTI y, I* RESTRICTI z, J jt);
extern I lcmIO(I n, I m, I* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I lcmQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, Q* RESTRICTI z, J jt);
extern I lcmXX(I n, I m, X* RESTRICTI x, X* RESTRICTI y, X* RESTRICTI z, J jt);
extern I lcmZZ(I n, I m, Z* RESTRICTI x, Z* RESTRICTI y, Z* RESTRICTI z, J jt);
extern I leBB(I n, I m, void* RESTRICTI x, void* RESTRICTI y, void* RESTRICTI z, J jt);
extern I leBD(I n, I m, B* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I leBI(I n, I m, B* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I leDB(I n, I m, D* RESTRICTI x, B* RESTRICTI y, B* RESTRICTI z, J jt);
extern I leDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I leDI(I n, I m, D* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I leIB(I n, I m, I* RESTRICTI x, B* RESTRICTI y, B* RESTRICTI z, J jt);
extern I leID(I n, I m, I* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I leII(I n, I m, I* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I leQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, B* RESTRICTI z, J jt);
extern I leSS(I n, I m, SB* RESTRICTI x, SB* RESTRICTI y, B* RESTRICTI z, J jt);
extern I leXX(I n, I m, X* RESTRICTI x, X* RESTRICTI y, B* RESTRICTI z, J jt);
extern I ltBB(I n, I m, void* RESTRICTI x, void* RESTRICTI y, void* RESTRICTI z, J jt);
extern I ltBD(I n, I m, B* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I ltBI(I n, I m, B* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I ltDB(I n, I m, D* RESTRICTI x, B* RESTRICTI y, B* RESTRICTI z, J jt);
extern I ltDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I ltDI(I n, I m, D* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I ltIB(I n, I m, I* RESTRICTI x, B* RESTRICTI y, B* RESTRICTI z, J jt);
extern I ltID(I n, I m, I* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I ltII(I n, I m, I* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I ltSS(I n, I m, SB* RESTRICTI x, SB* RESTRICTI y, B* RESTRICTI z, J jt);
extern I ltQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, B* RESTRICTI z, J jt);
extern I ltXX(I n, I m, X* RESTRICTI x, X* RESTRICTI y, B* RESTRICTI z, J jt);
extern I maxBD(I n, I m, B* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I maxBI(I n, I m, B* RESTRICTI x, I* RESTRICTI y, I* RESTRICTI z, J jt);
extern I maxDB(I n, I m, D* RESTRICTI x, B* RESTRICTI y, D* RESTRICTI z, J jt);
extern I maxDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I maxDI(I n, I m, D* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I maxIB(I n, I m, I* RESTRICTI x, B* RESTRICTI y, I* RESTRICTI z, J jt);
extern I maxID(I n, I m, I* RESTRICTI x, D* RESTRICTI y, I* RESTRICTI z, J jt);
extern I maxII(I n, I m, I* RESTRICTI x, I* RESTRICTI y, I* RESTRICTI z, J jt);
extern I maxQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, Q* RESTRICTI z, J jt);
extern I maxSS(I n, I m, SB* RESTRICTI x, SB* RESTRICTI y, SB* RESTRICTI z, J jt);
extern I maxXX(I n, I m, X* RESTRICTI x, X* RESTRICTI y, X* RESTRICTI z, J jt);
extern I minBD(I n, I m, B* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I minBI(I n, I m, B* RESTRICTI x, I* RESTRICTI y, I* RESTRICTI z, J jt);
extern I minDB(I n, I m, D* RESTRICTI x, B* RESTRICTI y, D* RESTRICTI z, J jt);
extern I minDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I minDI(I n, I m, D* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I minIB(I n, I m, I* RESTRICTI x, B* RESTRICTI y, I* RESTRICTI z, J jt);
extern I minID(I n, I m, I* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I minII(I n, I m, I* RESTRICTI x, I* RESTRICTI y, I* RESTRICTI z, J jt);
extern I minQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, Q* RESTRICTI z, J jt);
extern I minSS(I n, I m, SB* RESTRICTI x, SB* RESTRICTI y, SB* RESTRICTI z, J jt);
extern I minXX(I n, I m, X* RESTRICTI x, X* RESTRICTI y, X* RESTRICTI z, J jt);
extern I minusBB(I n, I m, B* RESTRICTI x, B* RESTRICTI y, I* RESTRICTI z, J jt);
extern I minusBD(I n, I m, B* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I minusBI(I n, I m, B* RESTRICTI x, I* RESTRICTI y, I* RESTRICTI z, J jt);
extern I minusBIO(I n, I m, B* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I minusDB(I n, I m, D* RESTRICTI x, B* RESTRICTI y, D* RESTRICTI z, J jt);
extern I minusDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I minusDI(I n, I m, D* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I minusIB(I n, I m, I* RESTRICTI x, B* RESTRICTI y, I* RESTRICTI z, J jt);
extern I minusID(I n, I m, I* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I minusII(I n, I m, I* RESTRICTI x, I* RESTRICTI y, I* RESTRICTI z, J jt);
extern I minusIIO(I n, I m, I* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I minusIO(I n, I m, I* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I minusQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, Q* RESTRICTI z, J jt);
extern I minusXX(I n, I m, X* RESTRICTI x, X* RESTRICTI y, X* RESTRICTI z, J jt);
extern I minusZZ(I n, I m, Z* RESTRICTI x, Z* RESTRICTI y, Z* RESTRICTI z, J jt);
extern I nandBB(I n, I m, void* RESTRICTI x, void* RESTRICTI y, void* RESTRICTI z, J jt);
extern I neAA(I n, I m, A* RESTRICTI x, A* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neBB(I n, I m, void* RESTRICTI x, void* RESTRICTI y, void* RESTRICTI z, J jt);
extern I neBD(I n, I m, B* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neBI(I n, I m, B* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neCC(I n, I m, void* RESTRICTI x, void* RESTRICTI y, void* RESTRICTI z, J jt);  // really B,C,C
extern I neCS(I n, I m, UC* RESTRICTI x, US* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neDB(I n, I m, D* RESTRICTI x, B* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neDI(I n, I m, D* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neIB(I n, I m, I* RESTRICTI x, B* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neID(I n, I m, I* RESTRICTI x, D* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neII(I n, I m, I* RESTRICTI x, I* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neSC(I n, I m, US* RESTRICTI x, UC* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neSS(I n, I m, S* RESTRICTI x, S* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neXX(I n, I m, X* RESTRICTI x, X* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neZZ(I n, I m, Z* RESTRICTI x, Z* RESTRICTI y, B* RESTRICTI z, J jt);
extern I norBB(I n, I m, void* RESTRICTI x, void* RESTRICTI y, void* RESTRICTI z, J jt);
extern I orBB(I n, I m, void* RESTRICTI x, void* RESTRICTI y, void* RESTRICTI z, J jt);
extern I plusBB(I n, I m, B* RESTRICTI x, B* RESTRICTI y, I* RESTRICTI z, J jt);
extern I plusBI(I n, I m, B* RESTRICTI x, I* RESTRICTI y, I* RESTRICTI z, J jt);
extern I plusBIO(I n, I m, B* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I plusBD(I n, I m, B* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I plusDB(I n, I m, D* RESTRICTI x, B* RESTRICTI y, D* RESTRICTI z, J jt);
extern I plusDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I plusDI(I n, I m, D* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I plusDX(I n, I m, DX* RESTRICTI x, DX* RESTRICTI y, DX* RESTRICTI z, J jt);
extern I plusIB(I n, I m, I* RESTRICTI x, B* RESTRICTI y, I* RESTRICTI z, J jt);
extern I plusID(I n, I m, I* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I plusII(I n, I m, I* RESTRICTI x, I* RESTRICTI y, I* RESTRICTI z, J jt);
extern I plusIIO(I n, I m, I* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I plusIO(I n, I m, I* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I plusQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, Q* RESTRICTI z, J jt);
extern I plusXX(I n, I m, X* RESTRICTI x, X* RESTRICTI y, X* RESTRICTI z, J jt);
extern I plusZZ(I n, I m, Z* RESTRICTI x, Z* RESTRICTI y, Z* RESTRICTI z, J jt);
extern I powBD(I n, I m, B* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I powBI(I n, I m, B* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I powDB(I n, I m, D* RESTRICTI x, B* RESTRICTI y, D* RESTRICTI z, J jt);
extern I powDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I powDI(I n, I m, D* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I powIB(I n, I m, I* RESTRICTI x, B* RESTRICTI y, I* RESTRICTI z, J jt);
extern I powID(I n, I m, I* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I powII(I n, I m, I* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I powQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, Q* RESTRICTI z, J jt);
extern I powXX(I n, I m, X* RESTRICTI x, X* RESTRICTI y, X* RESTRICTI z, J jt);
extern I powZZ(I n, I m, Z* RESTRICTI x, Z* RESTRICTI y, Z* RESTRICTI z, J jt);
extern I remDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I remII(I n, I m, I* RESTRICTI x, I* RESTRICTI y, I* RESTRICTI z, J jt);
extern I remID(I n, I m, I* RESTRICTI x, D* RESTRICTI y, I* RESTRICTI z, J jt);
extern I remQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, Q* RESTRICTI z, J jt);
extern I remXX(I n, I m, X* RESTRICTI x, X* RESTRICTI y, X* RESTRICTI z, J jt);
extern I remZZ(I n, I m, Z* RESTRICTI x, Z* RESTRICTI y, Z* RESTRICTI z, J jt);
extern I tymesBD(I n, I m, B* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I tymesBI(I n, I m, B* RESTRICTI x, I* RESTRICTI y, I* RESTRICTI z, J jt);
extern I tymesDB(I n, I m, D* RESTRICTI x, B* RESTRICTI y, D* RESTRICTI z, J jt);
extern I tymesDD(I n, I m, D* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I tymesDI(I n, I m, I* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I tymesIB(I n, I m, I* RESTRICTI x, B* RESTRICTI y, I* RESTRICTI z, J jt);
extern I tymesID(I n, I m, I* RESTRICTI x, D* RESTRICTI y, D* RESTRICTI z, J jt);
extern I tymesII(I n, I m, I* RESTRICTI x, I* RESTRICTI y, I* RESTRICTI z, J jt);
extern I tymesIIO(I n, I m, I* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I tymesIO(I n, I m, I* RESTRICTI x, I* RESTRICTI y, D* RESTRICTI z, J jt);
extern I tymesQQ(I n, I m, Q* RESTRICTI x, Q* RESTRICTI y, Q* RESTRICTI z, J jt);
extern I tymesXX(I n, I m, X* RESTRICTI x, X* RESTRICTI y, X* RESTRICTI z, J jt);
extern I tymesZZ(I n, I m, Z* RESTRICTI x, Z* RESTRICTI y, Z* RESTRICTI z, J jt);
extern I eqUU(I n, I m, C4* RESTRICTI x, C4* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqUS(I n, I m, C4* RESTRICTI x, US* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqSU(I n, I m, US* RESTRICTI x, C4* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqUC(I n, I m, C4* RESTRICTI x, UC* RESTRICTI y, B* RESTRICTI z, J jt);
extern I eqCU(I n, I m, UC* RESTRICTI x, C4* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neUU(I n, I m, C4* RESTRICTI x, C4* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neUS(I n, I m, C4* RESTRICTI x, US* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neSU(I n, I m, US* RESTRICTI x, C4* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neUC(I n, I m, C4* RESTRICTI x, UC* RESTRICTI y, B* RESTRICTI z, J jt);
extern I neCU(I n, I m, UC* RESTRICTI x, C4* RESTRICTI y, B* RESTRICTI z, J jt);
