/* Copyright 1990-2009, Jsoftware Inc.  All rights reserved.               */
/* Licensed use only. Any other use is in violation of copyright.          */
/*                                                                         */
/* Extern Declarations                                                     */

extern A jtabase1(J jt, A w);
extern A jtadot1(J jt, A w);
extern A jtaflag1(J jt, A w);
extern A jtarep(J jt, A w);
extern A jtaro(J jt, A w);
extern A jtarx(J jt, A w);
extern A jtasgzombq(J jt, A w);
extern A jtasgzombs(J jt, A w);
extern A jtassertq(J jt, A w);
extern A jtasserts(J jt, A w);
extern A jtdirectdefq(J jt, A w);
extern A jtdirectdefs(J jt, A w);
extern A jtaudittdisab(J jt, A w);
extern A jtbase1(J jt, A w);
extern A jtbdot(J jt, A w);
extern A jtbehead(J jt, A w);
extern A jtbinrep1(J jt, A w);
extern A jtbit1(J jt, A w);
extern A jtbitadv(J jt, A w);
extern A jtbox(J jt, A w);
extern A jtboxopen(J jt, A w);
extern A jtboxq(J jt, A w);
extern A jtboxs(J jt, A w);
extern A jtbreakfnq(J jt, A w);
extern A jtbreakfns(J jt, A w);
extern A jtbsdot(J jt, A w);
extern A jtbslash(J jt, A w);
extern A jtca(J jt, A w);
extern A jtcaro(J jt, A w);
extern A jtcallback(J jt, A w);
extern A jtcallbackx(J jt, A w);
extern A jtcant1(J jt, A w);
extern A jtcar(J jt, A w);
extern A jtcasev(J jt, A w);
extern A jtcatalog(J jt, A w);
extern A jtcder(J jt, A w);
extern A jtcderx(J jt, A w);
extern A jtcdf(J jt, A w);
extern A jtcdjt(J jt, A w);
extern A jtcdlibl(J jt, A w);
extern A jtcdot1(J jt, A w);
extern A jtcdproc1(J jt, A w);
extern A jtceil1(J jt, A w);
extern A jtcerrno(J jt, A w);
extern A jtconjug(J jt, A w);
extern A jtcork1(J jt, A w, A self);
extern A jtcpufeature(J jt, A w);
extern A jtcrc1(J jt, A w);
extern A jtcrccompile(J jt, A w);
extern A jtctq(J jt, A w);
extern A jtcts(J jt, A w);
extern A jtcurtail(J jt, A w);
extern A jtcvt0(J jt, A w);
extern A jtdbc(J jt, A w);
extern A jtdbcall(J jt, A w);
extern A jtdbcutback(J jt, A w);
extern A jtdberr(J jt, A w);
extern A jtdbetx(J jt, A w);
extern A jtdbjump(J jt, A w);
extern A jtdbnext(J jt, A w);
extern A jtdbq(J jt, A w);
extern A jtdbret(J jt, A w);
extern A jtdbrr1(J jt, A w);
extern A jtdbrun(J jt, A w);
extern A jtdbsig1(J jt, A w);
extern A jtdbstack(J jt, A w);
extern A jtdbstackz(J jt, A w);
extern A jtdbstepinto1(J jt, A w);
extern A jtdbstepout1(J jt, A w);
extern A jtdbstepover1(J jt, A w);
extern A jtdbstopq(J jt, A w);
extern A jtdbstops(J jt, A w);
extern A jtdbtrapq(J jt, A w);
extern A jtdbtraps(J jt, A w);
extern A jtdecrem(J jt, A w);
extern A jtdenseit(J jt, A w);
extern A jtdgrade1(J jt, A w);
extern A jtdigits10(J jt, A w);
extern A jtdispq(J jt, A w);
extern A jtdisps(J jt, A w);
extern A jtdl(J jt, A w);
extern A jtdllsymdat(J jt, A w);
extern A jtdllsymget(J jt, A w);
extern A jtdllsymset(J jt, A w);
extern A jtdomainerr1(J jt, A w);
extern A jtdrep(J jt, A w);
extern A jtdrx(J jt, A w);
extern A jtduble(J jt, A w);
extern A jtdx_test(J jt, A w);
extern A jtemend(J jt, A w);
extern A jtevmq(J jt, A w);
extern A jtevms(J jt, A w);
extern A jtex(J jt, A w);
extern A jtexec1(J jt, A w);
extern A jtexg(J jt, A w);
extern A jtexpn1(J jt, A w);
extern A jtfact(J jt, A w);
extern A jtfactor(J jt, A w);
extern A jtfh15(J jt, A w);
extern A jtfiller(J jt, A w);
extern A jtfix(J jt, A w, A self);
extern A jtfloor1(J jt, A w);
extern A jtfmt01(J jt, A w);
extern A jtfmt11(J jt, A w);
extern A jtfmt21(J jt, A w);
extern A jtfname(J jt, A w);
extern A jtfrombase64(J jt, A w);
extern A jtfsmvfya(J jt, A w);
extern A jtfullname(J jt, A w);
extern A jtfx(J jt, A w, A self);
extern A jtfxeach(J jt, A w, A self);
extern PRIM jtfxself[2];
extern A jtfxx(J jt, A w);
extern A jtgaussdet(J jt, A w);
extern A jtgausselm(J jt, A w);
extern A jtgb_test(J jt, A w);
extern A jtgemmtune(J jt, A w);
extern A jtgh15(J jt, A w);
extern A jtgrade1(J jt, A w);
extern A jtkeybox(J jt, A a, A w, A self);
extern A jtkeyheadtally(J jt, A a, A w, A self);
extern A jthalve(J jt, A w);
extern A jthash(J jt, A w);
extern A jthead(J jt, A w);
extern A jthexrep1(J jt, A w);
extern A jthgdiff(J jt, A w);
extern A jthost(J jt, A w);
extern A jthostio(J jt, A w);
extern A jthostne(J jt, A w);
extern A jticap(J jt, A w);
extern A jticvt(J jt, A w);
extern A jtiden(J jt, A w);
extern A jtidensb(J jt, A w);
extern A jtiepdoq(J jt, A w);
extern A jtiepdos(J jt, A w);
extern A jtiepq(J jt, A w);
extern A jtieps(J jt, A w);
extern A jtimmea(J jt, A w);
extern A jtimmex(J jt, A w);
extern A jtincrem(J jt, A w);
extern A jtintmod2(J, A, I);
extern A jtinttoe(J jt, A w);
extern A jtetoint(J jt, A w);
extern A jtiota(J jt, A w);
extern A jtisnan(J jt, A w);
extern A jtisempty(J jt, A w);
extern A jtisitems(J jt, A w);
extern A jtisnotempty(J jt, A w);
extern A jtjclose(J jt, A w);
extern A jtjdir(J jt, A w);
extern A jtjdot1(J jt, A w);
extern A jtjfatt1(J jt, A w);
extern A jtjferase(J jt, A w);
extern A jtjfiles(J jt, A w);
extern A jtjfperm1(J jt, A w);
extern A jtjfread(J jt, A w);
extern A jtjfsize(J jt, A w);
extern A jtjgetenv(J jt, A w);
extern A jtjgetx(J jt, A w);
extern A jtjgetpid(J jt, A w);
extern A jtjico1(J jt, A w);
extern A jtjiread(J jt, A w);
extern A jtjlock(J jt, A w);
extern A jtjlocks(J jt, A w);
extern A jtjmkdir(J jt, A w);
extern A jtnatoms(J jt, A w);
extern A jtjoff(J jt, A w);
extern A jtjopen(J jt, A w);
extern A jtjpr(J jt, A w);
extern A rank(J jt, A w);
extern A jtjregcomp(J jt, A w);
extern A jtjregerror(J jt, A w);
extern A jtjregfree(J jt, A w);
extern A jtjreghandles(J jt, A w);
extern A jtjreginfo(J jt, A w);
extern A jtjunlock(J jt, A w);
extern A jtjwait(J jt, A w);
extern A jtlamin1(J jt, A w);
extern A jtlcg_test(J jt, A w);
extern A jtlevel1(J jt, A w);
extern A jtloccre1(J jt, A w);
extern A jtlocexmark(J jt, A w);
extern A jtlock1(J jt, A w);
extern A jtlocmap(J jt, A w);
extern A jtlocname(J jt, A w);
extern A jtlocnc(J jt, A w);
extern A jtlocnl1(J jt, A w);
extern A jtlocpath1(J jt, A w);
extern A jtlocsizeq(J jt, A w);
extern A jtlocsizes(J jt, A w);
extern A jtlocswitch(J jt, A w);
extern A jtlogar1(J jt, A w);
extern A jtlrep(J jt, A w);
extern A jtlrx(J jt, A w);
extern A jtmag(J jt, A w);
extern A jtmap(J jt, A w);
extern A jtmat(J jt, A w);
extern A jtmema(J jt, A w);
extern A jtmemf(J jt, A w);
extern A jtmemo(J jt, A w);
extern A jtmemr(J jt, A w);
extern A jtmemu(J jt, A w);
extern A jtminv(J jt, A w);
extern A jtmmaxq(J jt, A w);
extern A jtmmaxs(J jt, A w);
extern A jtmr_test(J jt, A w);
extern A jtmt_test(J jt, A w);
extern A jtnameref(J, A, A);
extern A jtnc(J jt, A w);
extern A jtnch(J jt, A w);
extern A jtnegate(J jt, A w);
extern A jtnfb(J jt, A w);
extern A jtnfeoutstr(J jt, A w);
extern A jtnfes(J jt, A w);
extern A jtnl1(J jt, A w);
extern A jtnlsym(J jt, A w);
extern A jtnot(J jt, A w);
extern A jtnub(J jt, A w);
extern A jtnubind(J jt, A w);
extern A jtnubind0(J jt, A w);
extern A jtnubsieve(J jt, A w);
extern A jtnubsievesp(J jt, A w);
extern A on1(J jt, A w, A self);
extern A jtonm(J jt, A w);
extern A jtope(J jt, A w);
extern A jtoutparmq(J jt, A w);
extern A jtoutparms(J jt, A w);
extern A jtparse(J jt, A w);
extern A jtparsercalls(J jt, A w);
extern A jtpathchdir(J jt, A w);
extern A jtpathcwd(J jt, A w);
extern A jtpathdll(J jt, A w);
extern A jtpderiv1(J jt, A w);
extern A jtpeekdata(J jt, A w);
extern A jtpinv(J jt, A w);
extern A jtpix(J jt, A w, A self);
extern A jtplt(J jt, A w);
extern A jtpmarea1(J jt, A w);
extern A jtpmctr(J jt, A w);
extern A jtpmstats(J jt, A w);
extern A jtpmunpack(J jt, A w);
extern A jtpolar(J jt, A w);
extern A jtpoly1(J jt, A w);
extern A jtposq(J jt, A w);
extern A jtposs(J jt, A w);
extern A jtpparity(J jt, A w);
extern A jtppq(J jt, A w);
extern A jtpps(J jt, A w);
extern A jtprep(J jt, A w);
extern A jtprime(J jt, A w);
extern A jtprocarch(J jt, A w);
extern A jtprocfeat(J jt, A w);
extern A jtprx(J jt, A w);
extern A jtqpctr(J jt, A w);
extern A jtqpfreq(J jt, A w);
extern A jtqr(J jt, A w);
extern A jtranking(J jt, A w);
extern A jtrankle(J jt, A w);
extern A jtrat(J jt, A w);
extern A jtravel(J jt, A w);
extern A jtraze(J jt, A w);
extern A jtrazeh(J jt, A w);
extern A jtrazein(J jt, A w);
extern A jtrca(J jt, A w);
extern A jtrdot1(J jt, A w);
extern A jtrecip(J jt, A w);
extern A jtrect(J jt, A w);
extern A jtretcommq(J jt, A w);
extern A jtretcomms(J jt, A w);
extern A jtreverse(J jt, A w);
extern A same(J jt, A w);
extern A jtrinv(J jt, A w);
extern A jtrngraw(J jt, A w);
extern A jtrngseedq(J jt, A w);
extern A jtrngseeds(J jt, A w);
extern A jtrngselectq(J jt, A w);
extern A jtrngselects(J jt, A w);
extern A jtrngstateq(J jt, A w);
extern A jtrngstates(J jt, A w);
extern A jtroll(J jt, A w);
extern A jtrollx(J jt, A w);
extern A jtsb1(J jt, A w);
extern A jtsborder(J jt, A w);
extern A jtscind(J jt, A w);
extern A jtscriptstring(J jt, A w);
extern A jtscriptnum(J jt, A w);
extern A jtsclass(J jt, A w);
extern A jtscm00(J jt, A w);
extern A jtscm01(J jt, A w);
extern A jtscm10(J jt, A w);
extern A jtscm11(J jt, A w);
extern A jtscnl(J jt, A w);
extern A jtsct1(J jt, A w);
extern A jtscz1(J jt, A w);
extern A jtseclevq(J jt, A w);
extern A jtseclevs(J jt, A w);
extern A jtself1(J jt, A w);
extern A shape(J jt, A w);
extern A jtshift1(J jt, A w);
extern A jtsignum(J jt, A w);
extern A jtsiinfo(J jt, A w);
extern A jtslash(J jt, A w);
extern A jtsldot(J jt, A w);
extern A jtsnl(J jt, A w);
extern A jtsp(J jt, A w);
extern A jtsparse1(J jt, A w);
extern A jtspcount(J jt, A w);
extern A jtspfor(J jt, A w);
extern A jtspforloc(J jt, A w);
extern A jtsphwmk(J jt, A w);
extern A jtspit(J jt, A w);
extern A jtsqroot(J jt, A w);
extern A jtsquare(J jt, A w);
extern A jtstr0(J jt, A w);
extern A jtstype(J jt, A w);
extern A jtswap(J jt, A w);
extern A jtsymbrd(J jt, A w);
extern A jtsymbrdlock(J jt, A w);
extern A jtsymbrdlocknovalerr(J jt, A w);
extern A jtsympool(J jt, A w);
extern A jtsysparmq(J jt, A w);
extern A jtsysparms(J jt, A w);
extern A jtsysq(J jt, A w);
extern A jttable(J jt, A w);
extern A jttail(J jt, A w);
extern A tally(J jt, A w);
extern A jttco(J jt, A w);
extern A jttdot(J jt, A w);
extern A jtthorn1(J jt, A w);
extern A jtthorn1u(J jt, A w);
extern A jttlimq(J jt, A w);
extern A jttlims(J jt, A w);
extern A jttobase64(J jt, A w);
extern A jttocesu8(J jt, A w);
extern A jttomutf8(J jt, A w);
extern A jttou32(J jt, A w);
extern A jttoutf16(J jt, A w);
extern A jttoutf16x(J jt, A w);
extern A jttoutf32(J jt, A w);
extern A jttoutf8(J jt, A w);
extern A jttoutf8a(J, A, A);
extern A jttoutf8x(J jt, A w);
extern A jttrep(J jt, A w);
extern A jttrx(J jt, A w);
extern A jtts(J jt, A w);
extern A jtts0(J jt, A w);
extern A jttsit1(J jt, A w);
extern A jttss(J jt, A w);
extern A jtuco1(J jt, A w);
extern A jtunbin(J jt, A w);
extern A jtunlock1(J jt, A w);
extern A jtunname(J jt, A w);
extern A jtunparse(J jt, A w);
extern A jtunzero(J jt, A w);
extern A jtvaspz(J jt, A w);
extern A jtversq(J jt, A w);
extern A jtvi(J jt, A w);
extern A jtvib(J jt, A w);
extern A jtvip(J jt, A w);
extern A jtvs(J jt, A w);
extern A jtvslit(J jt, A w);
extern A jtvtrans(J jt, A w);
extern A jtwordil(J jt, A w);
extern A jtwords(J jt, A w, A self);
extern A jtxco1(J jt, A w);
extern A jtxepq(J jt, A w);
extern A jtxeps(J jt, A w);
extern A jtabase2(J jt, A a, A w);
extern A jtadot2(J jt, A a, A w);
extern A jtadverse(J jt, A a, A w);
extern A jtaes2(J jt, A a, A w);
extern A jtaflag2(J jt, A a, A w);
extern A jtagenda(J jt, A a, A w);
extern A jtagendai(J jt, A a, A w);
extern A jtamp(J jt, A a, A w);
extern A jtampco(J jt, A a, A w);
extern A jtanyebar(J jt, A a, A w);
extern A jtapplystr(J jt, A a, A w);
extern A jtatco(J jt, A a, A w);
extern A jtatop(J jt, A a, A w);
extern A jtbase2(J jt, A a, A w);
extern A jtbinrep2(J jt, A a, A w);
extern A jtbit(J jt, A a, A w);
extern A jtbit2(J jt, A a, A w);
extern A jtbitmatch(J jt, A a, A w);
extern A jtbitwiserotate(J jt, A a, A w);
extern A jtbitwiseshift(J jt, A a, A w);
extern A jtbitwiseshifta(J jt, A a, A w);
extern A jtboxcut0(J jt, A a, A w, A self);
extern A jtcant2(J jt, A a, A w);
extern A jtcd(J jt, A a, A w);
extern A jtcdot2(J jt, A a, A w);
extern A jtcdproc2(J jt, A a, A w);
extern A jtcolon(J jt, A a, A w);
extern A jtcork2(J jt, A a, A w, A self);
extern A jtcpufeature2(J jt, A a, A w);
extern A jtcrc2(J jt, A a, A w);
extern A jtcut2(J jt, A a, A w, A self);
extern A jtcut(J jt, A a, A w);
extern A jtdbrr2(J jt, A a, A w);
extern A jtdbsig2(J jt, A a, A w);
extern A jtdbstepinto2(J jt, A a, A w);
extern A jtdbstepout2(J jt, A a, A w);
extern A jtdbstepover2(J jt, A a, A w);
extern A jtdeal(J jt, A a, A w);
extern A jtdealx(J jt, A a, A w);
extern A jtdgrade2(J jt, A a, A w);
extern A jtdomainerr2(J jt, A a, A w);
extern A jtdot(J jt, A a, A w);
extern A jtdrop(J jt, A a, A w);
extern A jtebar(J jt, A a, A w);
extern A jteps(J jt, A a, A w);
extern A jtetoiso8601(J jt, A a, A w);
extern A jtiso8601toe(J jt, A a, A w);
extern A jteven(J jt, A a, A w);
extern A jtevger(J jt, A a, A w);
extern A jtexec2(J jt, A a, A w);
extern A jtexpand(J jt, A a, A w);
extern A jtexpn2(J jt, A a, A w, A self);
extern A jtfc2(J jt, A a, A w);
extern A jtfetch(J jt, A a, A w);
extern A jtfit(J jt, A a, A w);
extern A jtfixrecursive(J jt, A a, A w);
extern A jtfmt02(J jt, A a, A w);
extern A jtfmt12(J jt, A a, A w);
extern A jtfmt22(J jt, A a, A w);
extern A jtfold(J jt, A a, A w, A self);
extern A jtfoldZ(J jt, A a, A w, A self);
extern A jtforeign(J jt, A a, A w);
extern A jtforeignextra(J jt, A a, A w);
extern A jtfrom(J jt, A a, A w);
extern A jtfrombs(J jt, A a, A w);
extern A jtfromis(J jt, A a, A w);
extern A jtfromr(J jt, A a, A w);
extern A jtfromsd(J jt, A a, A w);
extern A jtfromss(J jt, A a, A w);
extern A jtfsm(J jt, A a, A w);
extern A jtgemmtune2(J jt, A a, A w);
extern A jtgenbitwiserotate(J jt, A a, A w);
extern A jtgenbitwiseshift(J jt, A a, A w);
extern A jtgenbitwiseshifta(J jt, A a, A w);
extern A jtgrade1p(J jt, A a, A w);
extern A jtgrade2(J jt, A a, A w);
extern A jthexrep2(J jt, A a, A w);
extern A jthgeom(J jt, A a, A w);
extern A jthook(J jt, A a, A w);
extern A jti1ebar(J jt, A a, A w);
extern A jtic2(J jt, A a, A w);
extern A jticap2(J jt, A a, A w);
extern A jtifbebar(J jt, A a, A w);
extern A jtifrom(J jt, A a, A w);
extern A jtindexof(J jt, A a, A w);
extern A jtintdiv(J jt, A a, A w);
extern A jtjdot2(J jt, A a, A w);
extern A jtjfappend(J jt, A a, A w);
extern A jtjfatt2(J jt, A a, A w);
extern A jtjfperm2(J jt, A a, A w);
extern A jtjfwrite(J jt, A a, A w);
extern A jtjico2(J jt, A a, A w);
extern A jtjiwrite(J jt, A a, A w);
extern A jtjregmatch(J jt, A a, A w);
extern A jtjregmatches(J jt, A a, A w);
extern A jtlamin2(J jt, A a, A w);
extern A jtlcapco(J jt, A a, A w);
extern A jtleft2(J jt, A a, A w);
extern A jtless(J jt, A a, A w);
extern A jtlink(J jt, A a, A w, A self);
extern A jtloccre2(J jt, A a, A w);
extern A jtlock2(J jt, A a, A w);
extern A jtlocnl2(J jt, A a, A w);
extern A jtlocpath2(J jt, A a, A w);
extern A jtlogar2(J jt, A a, A w);
extern A jtmatch(J jt, A a, A w);
extern A jtmdiv(J jt, A a, A w);
extern A jtmemu2(J jt, A a, A w);
extern A jtmemw(J jt, A a, A w);
extern A jtnamerefop(J jt, A a, A w);
extern A jtnl2(J jt, A a, A w);
extern A jtnotmatch(J jt, A a, A w);
extern A jtnouninfo2(J jt, A a, A w);
extern A jtobverse(J jt, A a, A w);
extern A jtodd(J jt, A a, A w);
extern A jtordstat(J jt, A a, A w);
extern A jtordstati(J jt, A a, A w);
extern A jtoutstr(J jt, A a, A w);
extern A jtover(J jt, A a, A w);
extern A jtpco2(J jt, A a, A w);
extern A jtpderiv2(J jt, A a, A w);
extern A jtpdt(J jt, A a, A w);
extern A jtpdtsp(J jt, A a, A w);
extern A jtpmarea2(J jt, A a, A w);
extern A jtpoly2(J jt, A a, A w, A self);
extern A jtqco2(J jt, A a, A w);
extern A jtqhash12(J jt, A a, A w);
extern A jtqq(J jt, A a, A w);
extern A jtrdot2(J jt, A a, A w);
extern A jtreaxis(J jt, A a, A w);
extern A jtreitem(J jt, A a, A w);
extern A jtrepeat(J jt, A a, A w);
extern A jtrepeatr(J jt, A a, A w);
extern A jtreshape(J jt, A a, A w);
extern A jtresidue(J jt, A a, A w, A self);
extern A jtrezero(J jt, A a, A w);
extern A jtright2(J jt, A a, A w);
extern A jtroot(J jt, A a, A w);
extern A jtrotate(J jt, A a, A w);
extern A jtsb2(J jt, A a, A w);
extern A jtscapco(J jt, A a, A w);
extern A jtscm002(J jt, A a, A w);
extern A jtscm012(J jt, A a, A w);
extern A jtscm102(J jt, A a, A w);
extern A jtscm112(J jt, A a, A w);
extern A jtsct2(J jt, A a, A w);
extern A jtscz2(J jt, A a, A w);
extern A jtself2(J jt, A a, A w);
extern A jtsetfv(J jt, A a, A w);
extern A jtsfrom(J jt, A a, A w);
extern A jtsmmcar(J jt, A a, A w);
extern A jtsmmis(J jt, A a, A w);
extern A jtsparse2(J jt, A a, A w);
extern A jtspecialatoprestart(J jt, A a, A w, A self);
extern A jtstitch(J jt, A a, A w);
extern A jtstitchsp2(J jt, A a, A w);
extern A jtsumebar(J jt, A a, A w);
extern A jttake(J jt, A a, A w);
extern A jttcap(J jt, A a, A w);
extern A jtthorn2(J jt, A a, A w);
extern A jttie(J jt, A a, A w);
extern A jttsit2(J jt, A a, A w);
extern A jtuco2(J jt, A a, A w);
extern A jtundco(J jt, A a, A w);
extern A jtunder(J jt, A a, A w);
extern A jtunlock2(J jt, A a, A w);
extern A jtunparsem(J jt, A a, A w);
extern A jtupon2(J jt, A a, A w, A self);
extern A jtupon2cell(J jt, A a, A w, A self);
extern A jtxco2(J jt, A a, A w);
extern A jtxdefn(J jt, A a, A w, A self);
extern A jtxrx(J jt, A a, A w);

extern A jtamend(J jt, A w);
extern A jtbitwise1(J jt, A w, A self);
extern A jtbitwiseinsertchar(J jt, A w, A self);
extern A jtcrcfixedleft(J jt, A w, A self);
extern A jtdetxm(J jt, A w, A self);
extern A jtdfs1(J jt, A w, A self);
extern A jtexppi(J jt, A w, A self);
extern A jtfsmfx(J jt, A w, A self);
extern A jthgcoeff(J jt, A w, A self);
extern A jthook1cell(J jt, A w, A self);
extern A jthook2cell(J jt, A a, A w, A self);
extern A jtmean(J jt, A w, A self);
extern A jtnum1(J jt, A w, A self);
extern A jtrazecut1(J jt, A w, A self);
extern A jtredcat(J jt, A w, A self);
extern A jtredravel(J jt, A w, A self);
extern A jtwd(J jt, A w, A self);

extern A jtapip(J jt, A a, A w);
extern A jtatomic1(J jt, A w, A self);
extern A jtatomic2(J jt, A a, A w, A self);
extern A jtbitwisechar(J jt, A a, A w, A self);
extern A jtcharfn2(J jt, A a, A w, A self);
extern A jtunquote(J jt, A a, A w, A self);
extern A jtdbunquote(J, A, A, A, L*);
extern A jtdfs2(J jt, A a, A w, A self);
extern A jteachl(J jt, A a, A w, A self);
extern A jteachr(J jt, A a, A w, A self);
extern A jtfslashatg(J jt, A a, A w, A self);
extern A jtimplocref(J jt, A a, A w, A self);
extern A jtnum2(J jt, A a, A w, A self);
extern A jtpolymult(J jt, A a, A w, A self);
extern A jtpowop(J jt, A a, A w, A self);
extern A jtrazecut0(J jt, A a, A w, A self);
extern A jtrazecut2(J jt, A a, A w, A self);
extern A jtrollk(J jt, A a, A w, A self);
extern A jtrollkx(J jt, A a, A w, A self);
extern A jtsumattymes1(J jt, A a, A w, A self);
extern A jtxop2(J jt, A a, A w, A self);
extern A jtassembleresults(J, I, A, A, A*, I, I, I, A, I, I, I);
extern I cachedmmult(J, D*, D*, D*, I, I, I, I);
extern void copyTT(void*, void*, I, I, I);
extern A jtac1(J, AF);
extern A jtac2(J, AF);
extern B jtadd2(J, F, F, C*);
extern I jtaii(J, A);
extern B jtaindex(J, A, A, I, A*);
extern A jtam1a(J, A, A, A, B);
extern A jtam1e(J, A, A, A, B);
extern A jtam1sp(J, A, A, A, B);
extern A jtamna(J, A, A, A, B);
extern A jtamne(J, A, A, A, B);
extern A jtamnsp(J, A, A, A, B);
extern A jtapv(J, I, I, I);
extern A jtapvwr(J, I, I, I);
extern A jtascan(J, C, A);
extern A jtaslash(J, C, A);
extern A jtaslash1(J, C, A);
extern A jtatab(J, C, A, A);
extern AF jtatcompf(J, A, A, A);
extern void jtauditmemchains(J);
extern B jtb0(J, A);
extern A jtbcvt(J, C, A);
extern B* jtbfi(J, I, A, B);
extern D jtbindd(J, D, D);
extern B jtbitwisecharamp(J, UC*, I, UC*, UC*);
extern B jtboxatop(J, A);
extern A jtcelloffset(J, AD* RESTRICT, AD* RESTRICT);
extern A jtcharmap(J, A, A, A);
extern B jtcheckmf(J);
extern B jtchecksi(J);
extern A jtclonelocalsyms(J, A);
extern A jtclonevirtual(J, A);
extern I jtcompare(J, A, A);
extern A jtconnum(J, I, C*);
extern I jtcountnl(J);
extern A jtcpa(J, B, A);
extern A jtcreatecycliciterator(J, A, A);
extern A jtcrelocalsyms(J, A, A, I, I, I);
extern A jtcstr(J, C*);
extern A jtcvt(J, I, A);
extern B jtccvt(J, I, A, A*);
extern A jtcvz(J, I, A);
extern A jtdaxis(J, I, A);
extern A jtddtokens(J, A, I);
extern DC jtdeba(J, C, void*, void*, A);
extern void jtdebdisp(J, DC);
extern void jtdebz(J);
extern A jtdecorate(J, A, I);
extern A jtdfss1(J, A, A, A);
extern A jtdfss2(J, A, A, A, A);
extern D jtdgamma(J, D);
extern D jtdgcd(J, D, D);
extern D jtdlcm(J, D, D);
extern A jtdropr(J, I, A);
extern B jtecvt(J, D, I, int*, int*, C*);
extern B jtecvtinit(J);
extern A jtenqueue(J, A, A, I);
extern B jtequ(J, A, A);
extern B jtequ0(J, A, A);
extern A jtev1(J, A, C*);
extern A jtev2(J, A, A, C*);
extern A jteva(J, A, C*);
extern A jteval(J, C*);
extern A jtevc(J, A, A, C*);
extern A jtevery(J jt, A w, A self);
extern A jtevery2(J jt, A a, A w, A self);
extern A jteveryself(J jt, A w, A self);
extern A jtevery2self(J jt, A a, A w, A self);
extern void jtexpostvirtual(J, A, A, I);
extern A jtext(J, B, A);
extern A jtexta(J, I, I, I, I);
extern A jtextnvr(J);
extern I jtfa(J, AD* RESTRICT, I);
extern A jtfdef(J, I, C, I, AF, AF, A, A, A, I, I, I, I);
extern void jtfh(J, A);
extern void jtfillv(J, I, I, C*); /* "fill" name conflict on Mac             */
extern A jtfindnl(J, I);
extern I jtfnum(J, A);
extern A jtfolk(J, A, A, A); /* "fork" name conflict under UNIX         */
extern A jtfrombsn(J, A, A, I);
extern A jtfrombu(J, A, A, I);
extern A jtfxeachv(J, I, A);
extern RESTRICTF A jtga(J, I, I, I, I*);
extern RESTRICTF A jtgaf(J, I);
extern RESTRICTF A jtgafv(J, I);
extern A jtgadv(J, A, C);
extern RESTRICTF A jtgah(J, I, A);
extern A jtgc(J, A, A*);
extern I jtgc3(J, A*, A*, A*, A*);
extern A jtgconj(J, A, A, C);
extern B jtgerexact(J, A);
extern B jtglobinit(J);
extern B jthasimploc(J, A);
extern I jti0(J, A);
extern A jtifb(J, I, B* RESTRICT);
extern I jtigcd(J, I, I);
extern I jtilcm(J, I, I);
extern A jtincorp(J, A);
extern A jtindexnl(J, I);
extern A jtindexofprehashed(J, A, A, A);
extern A jtindexofss(J, I, A, A);
extern A jtindexofsub(J, I, A, A);
extern A jtindexofxx(J, I, A, A);
extern A jtinpl(J, B, I, C*);
extern A jtiocol(J, I, A, A);
extern A jtiovsd(J, I, A, A);
extern A jtiovxs(J, I, A, A);
extern D jtintpow(J, D, I);
extern A jtirs1(J, A, A, I, AF);
extern A jtirs2(J, A, A, A, I, I, AF);
extern A jtjerrno(J);
extern A jtjgets(J, C*);
extern C jtjinit2(J, int, C**);
extern A jtinv(J, A, I);  // second arg is forced to 0 for initial call
extern F jtjope(J, A, C*);
extern L* jtjset(J, C*, A);
extern void jtjsigd(J, C*);
extern void jtjsignal(J, I);
extern void jtjsignal3(J, I, A, I);
extern B jtlocdestroy(J, A);
extern I jtmaxtype(J, I, I);
extern B jtmeminit(J);
extern void jtmf(J, A);
extern A jtmkwris(J, A);
extern I jtmult(J, I, I);
extern A jtnamerefacv(J, A, L*);
extern A jtnfs(J, I, C*);
extern I jtnotonupperstack(J, A);
extern A jtodom(J, I, I, I* RESTRICT);
extern A jtparsea(J, A*, I);
extern B jtparseinit(J);
extern A jtparsex(J, A*, I, CW*, DC);
extern A jtpaxis(J, I, A);
extern A jtpcvt(J, I, A);
extern A jtpee(J, A*, CW*, I, I, DC);
extern A jtpfill(J, I, A);
extern A jtpind(J, I, A);
extern B jtpinit(J);
extern I jtpiplocalerr(J, A);
extern void jtpmrecord(J, A, A, I, int);
extern D jtpospow(J, D, D);
extern B jtpreparse(J, A, A*, A*);
extern B jtprimitive(J, A);
extern L* jtprobe(J, I, C*, UI4, A);
extern L* jtprobedel(J, I, C*, UI4, A);
extern L* jtprobeis(J, A, A);
extern L* jtprobeislocal(J, A);
extern L* jtprobeisquiet(J, A, A);
extern L* jtprobelocal(J, A, A);
extern I jtprod(J, I, I*);
extern I jtqcompare(J, Q, Q);
extern I jtra(AD* RESTRICT, I);
extern A jtras(J, AD* RESTRICT);
extern A jtra00s(J, AD* RESTRICT);
extern A jtrank1ex(J, AD* RESTRICT, A, I, AF);
extern A jtrank1ex0(J, AD* RESTRICT, A, AF);
extern A jtrank2ex(J, AD* RESTRICT, AD* RESTRICT, A, UI, AF);
extern A jtrank2ex0(J, AD* RESTRICT, AD* RESTRICT, A, AF);
extern A jtrd(J, F, I, I);
extern A jtrealize(J, A);
extern A jtredcatcell(J, A, I);
extern D jtremdd(J, D, D);
extern I jtremid(J, I, D);
extern A jtrifvs(J, AD* RESTRICT);
extern B jtredef(J, A, L*);
extern B jtrnginit(J);
extern B jtsbtypeinit(J);
extern A jtsc(J, I);
extern A jtsc4(J, I, I);
extern A jtscansp(J, A, A, AF);
extern A jtscb(J, B);
extern A jtscc(J, C);
extern A jtscf(J, D);
extern B jtscheck(J, A);
extern A jtscx(J, X);
extern A jtscib(J, I);
extern B jtsesminit(J);
extern A jtsfn(J, B, A);
extern A jtsfne(J, A);
extern void jtshowerr(J);
extern A jtsparseit(J, A, A, A);
extern I jtspbytesinuse(J);
extern I jtspstarttracking(J);
extern void jtspendtracking(J);
extern B jtspc(J);
extern A jtspella(J, A);
extern A jtspellcon(J, I);
extern A jtspellout(J, C);
extern B jtspfree(J);
extern B jtspmult(J, A*, A, A, C, I, I, I, I);
extern A jtsprank1(J, A, A, I, AF);
extern A jtsprank2(J, A, A, A, I, I, AF);
extern A jtssingleton(J, A, A, A, RANK2T, RANK2T);
extern A jtssingleton1(J, A, A);
extern A jtstcreate(J, C, I, I, C*);
extern F jtstdf(J, A);
extern A jtstfind(J, I, C*, I);
extern A jtstfindcre(J, I, C*, I);
extern A jtstr(J, I, C*);
extern A jtstrq(J, I, C*);
extern I jtsumattymesprods(J, I, void*, void*, I, I, I, I, I, void*);
extern B jtsymbinit(J);
extern L* jtsymbis(J, A, A, A);
extern L* jtsymbisdel(J, A, A, A);
extern B jtsymext(J, B);
extern void jtsymfreeha(J, A);
extern L* jtsymnew(J, LX*, LX);
extern A jtsybaseloc(J, A);
extern L* jtsyrd(J, A, A);
extern L* jtsyrd1(J, I, C*, UI4, A);
extern A jtsyrdforlocale(J, A);
extern A jtsyrd1forlocale(J, I, C*, UI4, A);
extern L* jtsyrdfromloc(J, A, A);
extern L* jtsyrdnobuckets(J, A);
extern A jttaker(J, I, A);
extern D jttceil(J, D);
extern D jttfloor(J, D);
extern I jtthv(J, A, I, C*);
extern A jttoc1(J, B, A);
extern void jttoutf8w(J, C*, I, US*);
extern void jttpop(J, A*);
extern A* jttpush(J, AD* RESTRICT, I, A*);
extern B jttrd(J jt, A w);
extern A* jttg(J, A*);
extern A jttokens(J, A, I);
extern A jtunDD(J, A);
extern B jtunlk(J, I);
extern A jtunwordil(J, A, A, I);
extern A jtv2(J, I, I);
extern A jtva2s(J, A, A, C, VF, I, I, I, I, I);
extern VA2 jtvar(J, A, I, I);
extern A jtvasp(J, A, A, C, VF, I, I, I, I, I, I, I, I, I);
extern B jtvc1(J, I, US*);
extern A jtvci(J, I);
extern A jtvec(J, I, I, void*);
extern A jtvecb01(J, I, I, void*);
extern F jtvfn(J, F);
extern A jtvger2(J, C, A, A);
extern A jtvirtual(J, AD* RESTRICT, I, I);
extern B jtvnm(J, I, C*);
extern void jtwri(J, I, C*, I, C*);
extern B jtxlinit(J);
extern B jtxoinit(J);
extern B jtxsinit(J);

extern B all0(A);
extern B all1(A);
extern I allosize(A);
extern I atoplr(A);
extern I atype(I);
extern I boxat(A, I, I, I);
extern I bsum(I, B*);
extern C cf(A);
extern C cl(A);
extern CR condrange(I*, I, I, I, I);
extern CR condrange2(US*, I, I, I, I);
extern CR condrange4(C4*, I, I, I, I);
extern B evoke(A);
extern void forcetomemory(void*);
extern UI hic(I, UC*);
extern UI hic2(I, UC*);
extern UI hic4(I, UC*);
extern I hsize(I);
extern J jinit(void);
extern void jsto(J, I, C*);
extern void jstpoll(J);
extern void jststop(J);
extern I level(A);
extern I levelle(A, I);
extern void mvc(I, void*, I, void*);
extern B nameless(A);
extern D qpf(void);
extern A relocate(I, A);
extern I remii(I, I);
extern C spellin(I, C*);
extern void spellit(C, C*);
extern I smmallosize(A);
extern void smmfrr(A);
extern void sortiq1(I*, I);
extern I strtoI10s(I, C*);
extern D tod(void);
extern void va1primsetup(A);
extern void va2primsetup(A);
extern B vlocnm(I, C*);
extern D xdouble(X);
#define memcmpne(s, t, l) (!!memcmp((s), (t), (l)))

struct Bd1 {
    I hdr[AKXR(0) / SZI];
    D v[1];
};
struct Bd2;
extern struct Bd2 Ba0j1;
#define a0j1 ((A)&Ba0j1)
extern struct Bd1 Bainf;
#define ainf ((A)&Bainf)
extern I Baqq[];
#define aqq ((A)&Baqq)
extern I Bmtv[];
#define mtv ((A)&Bmtv)
extern I Bmtm[];
#define mtm ((A)&Bmtm)
extern I Basgnlocsimp[];
#define asgnlocsimp ((A)&Basgnlocsimp)
extern I Basgngloname[];
#define asgngloname ((A)&Basgngloname)
extern I Basgnforceglo[];
#define asgnforceglo ((A)&Basgnforceglo)
extern I Basgnforcegloname[];
#define asgnforcegloname ((A)&Basgnforcegloname)
extern I Bimax[];
#define imax ((A)&Bimax)
extern I Bmark[];
#define mark ((A)&Bmark)
extern C breakdata;
extern I Bchrcolon[];
#define chrcolon ((A)&Bchrcolon)
extern I Bchrspace[];
#define chrspace ((A)&Bchrspace)
extern I validitymask[];
extern C ctype[];
extern const double dzero;
extern D inf;
extern D infm;
extern I Biv0[];
#define iv0 ((A)&Biv0)
extern I Biv1[];
#define iv1 ((A)&Biv1)
extern D jnan; /* "nan" name conflict under Solaris       */
extern A mnuvxynam[6];
extern void moveparseinfotosi(J);
extern I Bnum[][8];
#define zeroionei(n) ((A)(Bnum + (n)))
#define num(n) ((A)(Bnum + 2 + (n)-NUMMIN))
#define I1mem (Bnum[1][7])  // 1 stored in memory
extern struct Bd1 Bnumvr[];
#define numvr(n) ((A)(Bnumvr + (n)))
extern struct Bd1 Bonehalf;
#define onehalf ((A)&Bonehalf)
extern D pf;
extern struct Bd1 Bpie;
#define pie ((A)&Bpie)
extern PRIM primtab[];
extern const UI4 shortrange[3][4];
extern Z zeroZ;
extern I oneone[2];
extern A zpath;
extern I iotavec[IOTAVECLEN];  // ascending integers, starting at IOTAVECBEGIN
extern VARPSA rpsnull;
extern PRIM sfn0overself;
